apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      restartPolicy: Always
      containers:
        - name: bot
          image: IMAGE_PLACEHOLDER
          env:
            - name: ENV
              value: ENV_PLACEHOLDER